//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigXmlInsertTableSample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SampledataEntities : DbContext
    {
        public SampledataEntities()
            : base("name=SampledataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book_story> book_story { get; set; }
    
        public virtual ObjectResult<SP_Storybook_Result> SP_Storybook(string xmlStr)
        {
            var xmlStrParameter = xmlStr != null ?
                new ObjectParameter("xmlStr", xmlStr) :
                new ObjectParameter("xmlStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Storybook_Result>("SP_Storybook", xmlStrParameter);
        }
    }
}
